# Generated by Django 3.1.7 on 2021-04-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MqttData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
